### ISSUE TITLE
Docusign throws this error on update on ApiClient.RequestJWTUserToken

### ISSUE THREAD

**Issue by umakesan** [docusign/eg-01-csharp-jwt-framework#3]
DocuSign Exception!
    Reason: 400
    Error Reponse: {"error":"invalid_grant","error_description":"no_valid_keys_or_signatures"}

**Comment by LarryKlugerDS** [comment]
Hi, You say "on update." Have you been able to obtain an access token via JWT grant at all?

From the error message, it sounds like you don't have the RSA private key configured correctly.

**Comment by umakesan** [comment]
Hey sorry figured it out yes that was the mistake I had to regenerate the
RSA private key for some reason and then it started working

**Comment by LarryKlugerDS** [comment]
Glad to help!
